# Generated by Django 3.0 on 2019-12-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ajio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_brand', models.CharField(max_length=64, null=True, unique=True)),
                ('prod_name', models.CharField(max_length=64, null=True)),
                ('prod_price', models.FloatField(null=True)),
                ('prod_discount', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='flipkart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_brand', models.CharField(max_length=64, null=True, unique=True)),
                ('prod_name', models.CharField(max_length=64, null=True)),
                ('prod_price', models.FloatField(null=True)),
                ('prod_discount', models.IntegerField(null=True)),
            ],
        ),
    ]
