# Generated by Django 3.0 on 2019-12-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopchoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajio',
            name='prod_discount',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='ajio',
            name='prod_price',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='flipkart',
            name='prod_discount',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='flipkart',
            name='prod_price',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
