# Generated by Django 3.0 on 2019-12-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopchoice', '0002_auto_20191215_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajio',
            name='prod_brand',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='flipkart',
            name='prod_brand',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
